debug: true
spring:
  datasource:
              url: jdbc:mysql://127.0.0.1:3306/sjwatch?useUnicode=true&characterEncoding=UTF-8
              username: root
#              password: 123456
              password: "!Ww58879576"
              driver-class-name: com.mysql.jdbc.Driver
  #removing null values form json response
  jackson:
          default-property-inclusion: NON_NULL

  thymeleaf:
            cache: true
            check-template: true
            check-template-location: true
            enabled: true
            encoding: UTF-8
            mode: HTML5
            prefix: classpath:/templates/mall/
            suffix: .html
            servlet:
              content-type: text/html

redis:
        database: 0
#        host: 192.168.0.157
        host: 127.0.0.1
        port: 6379
        password: 123456
        timeout: 3000
        expire: 1000
        pool:
            max-active: 8
            max-wait: -1
            max-idle: 8
            min-idle: 0

server:
        port: 80

mybatis:
  type-aliases-package: com.boiledcoffee.sjwatch.model
  mapper-locations: classpath:mybatis/mapper/*.xml

logging:
  level:
    com.boiledcoffee.sjwatch: DEBUG
  file: ./logs/sjwathc.log
  root: INFO

qiniu:
  ak: 6bpjaMgBu6ChmdHzr88nG0VYIHMtQgM8iMPJ0fJZ
  sk: 7l7arEeXadKEVSxBX3WIx-xKPgsVQvvKuuExpXGu
  bucket: sjwatch

oss:
  ak: LTAIVzLpulIYD9cW
  sk: vC2BUofCErvKx4RmBl19YNLrRp3MZW
  bucket: sjwatch
  expiration: 24

ali-sms:
  ak: LTAIWLvciApdcvJ5
  sk: diJzKmp3ZtN1Qxy7YDIKDlD7bkUqPH
  signName: "张俊洪"
  templateCode: "SMS_142621832"

tx-sms:
  appId: 1400183182
  appKey: 8e2852e06cd9e8505c54775ebf0d7463

sj-config:
  # 用户token有效时长 单位小时
  tokenValidTime: 2
  # 短信验证码有效时长 单位分钟
  smsValidTime: 5